---
- name: Download node.js source
  get_url: url={{ node.source }} dest=/usr/src/node.tar.gz force=no

- name: Create a directory for node.js source files
  file: path=/usr/src/node state=directory

- name: Unpack node.js source
  unarchive: src=/usr/src/node.tar.gz dest=/usr/src/node copy=no
    creates=/usr/local/bin/node

- name: Install node.js
  command: "{{ item }}"
  args:
    chdir: /usr/src/node/node-v0.10.36
    creates: /usr/local/bin/node
  with_items:
    - ./configure
    - make
    - make install

- name: Set NODE_HOME
  template:
    src: node.sh.j2
    dest: "/etc/profile.d/node.sh"

- name: Install npm packages
  shell: "/usr/local/bin/npm install -g {{ item }}"
  with_items: npm.modules
